### PR TITLE
Tweak a little

### PR DESCRIPTION
**Pull request by rejasupotaro**
# Overview

I read the implementation. The implementation looks good 👍 
I tweaked a little while reading. However, most of the changes can be preference issues 💅 
You don't have to adopt my changes if you don't like this change (I'm happy to revert commits or close 🤗)

# Major changes

- Make fields non-null as much as possible to avoid unnecessary null checks
- Acronyms shouldn't be UPPERCASE: https://github.com/cookpad/styleguide/blob/master/java.en.md#acronyms
- Omit redundant return types
- Remove unnecessary `catch` statements in `Net.kt`
- Rename `traverseView ` => `replaceTextRecursively`
  - Because this method has a side-effect
  - Make `process` optional because it seems to be exposed for testing

### CODE REVIEW

**Comment by rejasupotaro** [comment]
@VictorAlbertos @pabloppp Please review 🙏 

Don't forget renaming package before publishing (`org.cookpad` => `com.cookpad`) (e.g. Puree is `com.cookpad.puree`)

**Comment by pabloppp** [comment]
I like the changes you've made. As you said they are mostly nits and small code improvements, but they make the code a little bit nicer (specially removing the nullable maps).
Also wrapping the try/catches in a return statement is a clever use of Kotlin power!!
Thanks!! 🙇

**Comment by rejasupotaro** [comment]
Thank you for reviewing 🍻 ✨

**Comment by VictorAlbertos** [comment]
Thanks @rejasupotaro for the PR 👍

**Pull request merged**
